
springdoc:
  api-docs:
    path: /v3/api-docs # API 文档的访问路径
  swagger-ui:
    path: /swagger-ui.html # Swagger UI 的访问路径
    operations-sorter: alpha # 按字母顺序对操作排序
    tags-sorter: alpha # 按字母顺序对标签排序
  paths-to-match:
    - /** # 匹配需要生成文档的接口路径